Restore the ''import "unsafe'' removed in 1af712c9bc79d26f6aa5cf6e3747571e5116d7af. This was causing build failures with tools dependent on Flatbuffers in Go. E.g. go/src/github.com/google/flatbuffers/go/sizes.go:50: undefined: unsafe in unsafe.Pointer